name: sistema-cobranza
services:
- name: backend
  source_dir: backend-separado
  github:
    repo: Tunic3567/propio0-sistema
    branch: main
    deploy_on_push: true
  build_command: npm install
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-512
  http_port: 4000
  envs:
  - key: MONGO_URI
    scope: RUN_TIME
  - key: NODE_ENV
    value: production
    scope: RUN_TIME

static_sites:
- name: frontend
  source_dir: frontend-separado
  github:
    repo: Tunic3567/propio0-sistema
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  output_dir: dist
  envs:
  - key: VITE_API_BASE_URL
    scope: BUILD_TIME

